### PR TITLE
Leisure=track and areas

### PR DESCRIPTION
**Pull request by Phyks**
Superseeds #472 (started from the same code base). @Florimondable please merge this one if render is ok for you.

Screenshots : (only layers are landuse and leisure_track)

http://localhost:6789/cyclosm-cartocss-style/#19/47.20938/-1.51680

http://localhost:6789/cyclosm-cartocss-style/#19/48.82544/2.48265

http://localhost:6789/cyclosm-cartocss-style/#18/48.82623/2.41265

http://localhost:6789/cyclosm-cartocss-style/#19/47.22952/-1.59251

### CODE REVIEW

**Comment by Florimondable** [comment]
Where is the glow effect around line track ?
like here https://user-images.githubusercontent.com/47089717/101991366-93676380-3cac-11eb-970e-07befee24280.png

**Comment by Phyks** [comment]
I was finding it misleading and removed it, especially on https://user-images.githubusercontent.com/3856586/107851588-6b5ec280-6e0b-11eb-9a85-6428dd12d4a4.png.

No strong opinion here, I can restore it as well (which color? The purple overlay or the usual color from https://user-images.githubusercontent.com/47089717/101991366-93676380-3cac-11eb-970e-07befee24280.png ?)

**Comment by Florimondable** [comment]
the purple

**Comment by Phyks** [comment]
Done:

**Pull request merged**
