### PR TITLE
Add dashline outline on path like way tunnels

### LINKED ISSUE #492: Hard to see tunnels: cycleways on different levels look like they cross each other
Where a cycleway passes under another through a tunnel, the rendering doesn't clearly show that there is a tunnel. This makes it look as if the cycleways cross instead of one going underneath the other.

Example ([OSM](https://www.openstreetmap.org/#map=19/53.19189/5.78003&layers=N)):

Screenshot from 2021-01-16 14-19-35

It does look like tunnels are in a lighter blue, but I find it hard to tell.

OSM-Carto for comparison:

Screenshot from 2021-01-16 14-19-46

-----

Nice to see the CyclOSM layer on openstreetmap.org as well. I find it very useful as a mapper to quickly see different renderings styles for different purposes after working on an area. :+1:

### PR DESCRIPTION
**Pull request by Florimondable**
#fix #492 

Screenshot_20210120_230251
Screenshot_20210120_230230
Screenshot_20210120_230156

The outline for bridges is also little wider.
Screenshot_20210120_230030

### CODE REVIEW

**Comment by Florimondable** [comment]
Add dashline for path and bridleway, here a case with a segregated path :
Screenshot_20210120_231721


Remove dashline for footway, otherwise it would be too much in city :
Screenshot_20210120_231926

**Comment by Phyks** [comment]
What about making tunnel blue lighter as well?

**Comment by Florimondable** [comment]
> What about making tunnel blue lighter as well?

It's already slightly lighter

**Comment by Phyks** [comment]
It is, but I would make the contrast a bit clearer. This would help distinguish the two blue tones even on bad quality screens (smartphones for instance).

**Comment by Florimondable** [comment]
ok,
Screenshot_20210122_155900
Screenshot_20210122_155819
Screenshot_20210122_155737

**Comment by Phyks** [comment]
Thanks!

**Pull request merged**
