### PR TITLE
Render mtb:name when available and no name is known

### LINKED ISSUE #533: render mtb:name
Hi, it's possible view the tag mtb:name? from https://wiki.openstreetmap.org/wiki/Mountain_biking

thanks

### PR DESCRIPTION
**Pull request by Phyks**
See https://www.openstreetmap.org/way/691640892#map=15/48.9693/7.7907

mtb_name

Fix #533.

### CODE REVIEW

**Comment by Florimondable** [comment]
13% of mtb:name ways have also a name, may be we should concatenate instead of picking one ?

**Comment by Phyks** [comment]
There is a total of 8093 ways with `mtb:name` value according to https://taginfo.openstreetmap.org/keys/mtb%3Aname.

From them, there are only 646 which have a `mtb:name` value different from the `name` value:

```
osm=> SELECT COUNT(*) FROM planet_osm_line WHERE highway IS NOT NULL and name IS NOT NULL and name != tags->'mtb:name';
 count
-------
   646
``` 

which is 8%.

So about 5% which are bad tagging (duplicate values) and 8% which might have a real meaning. I'm fetching some such examples at the moment to gauge how different the two values are.

**Comment by Phyks** [comment]
Here is an extract:

```
 Galleria 100 Croci                                 | Galleria
 Galleria 100 Croci                                 | Galleria
 sentiero 351 - Aprica - Monte Belvedere (e Caio)   | Caio
 Pilegrimsleden                                     | Svinestien
 Stoptrail                                          | Milky Way - pt. 3
 Camí de l'Algepsar                                 | Pista Toritos
 Sender del Collado                                 | Lombriz
 Rue de Soultz                                      | Soultzer Bike 85km 2010
 Turistvegen                                        | Gråkallstien
 Turistvegen                                        | Gråkallstien
 Rue du Mattenthal                                  | Soultzer Bike 85km 2010
 Saponetta                                          | Discesa Rivodora
 Rue des Châteaux                                   | Soultzer Bike 85km 2010
 Kellersiepenweg                                    | Kellersiepen Trail
 Kellersiepenweg                                    | Kellersiepen Trail
 Kellersiepenweg                                    | Kellersiepen Trail
 Via Sacra                                          | PS2
 Via Sacra                                          | PS2
 Via Sacra                                          | PS2
 Rogger Miegge                                      | La Verte de Gilly
 Trombino                                           | La Fossa
 Sentiero della Buca dei Banditi                    | I Tavolini
 Nedre Kanonvei                                     | Kanonstien
 Mother Logans Road                                 | Bay of Fires Trail
 Route forestière du Bois des Guibertes             | n°32 - Bois des Guibertes
 Route des Cochers                                  | Crêtes de Zore
 Jägerpfad                                          | Kohlhoftrails
 Jägerpfad                                          | Kohlhoftrails
 Posseltslustpfad                                   | Kohlhoftrails
 Rue des Traineaux                                  | Crêtes de Zore
 Трасса СДЮШОР "Буревестник-ЮМ" (5 км)              | Франция
 Трасса СДЮШОР "Буревестник-ЮМ" (5 км)              | Франция
 DH Coniglio                                        | Coniglio
 DH Coniglio                                        | Coniglio
 DH Coniglio                                        | Coniglio
 Devilstrail                                        | Devils Trail
 Kill me - thrill me                                | Rød nedkørsel
 Flow Country                                       | Flow Country Trail
 Мусорка                                            | Урна
 Sjøveien                                           | Linnekastet
 Orrido                                             | diagonale
 Orrido                                             | orrido
 XC Dotrščina                                       | XC singletrack
 Suolijärven luontopolku                            | Kielletty
 Suolijärven luontopolku                            | Kielletty
 Suolijärven luontopolku                            | Kielletty
 Suolijärven luontopolku                            | Kielletty
 Suolijärven luontopolku                            | Kielletty
 Suolijärven luontopolku                            | Kielletty
 Suolijärven luontopolku                            | Kielletty
 Camino al Cristo                                   | Ruta MTB Cerro San Pedro
 Camino al Teatro al Aire Libre                     | Ruta MTB Cerro San Pedro
```

Some are real different names, some are just typographic changes.

**Comment by Florimondable** [comment]
Ok for merging.

**Pull request merged**
