### PR TITLE
Polishing and bug fixes : POI icons, surfaces, highway in tunnels

### LINKED ISSUE #185: More visible bicycle shop icon
Bicycle shops should be more visible in the map.

### LINKED ISSUE #234: Cycleway not rendered through tunnel
Hi
https://www.cyclosm.org/#map=15/51.3639/-2.3492

Is there a specific reason Cycleways are not rendered through tunnels?
https://www.openstreetmap.org/way/39042117#map=17/51.36990/-2.36594

### LINKED ISSUE #239: Pedestrian area in grey
Pedestrian area are rendered in light green (because mixed between pedestrian and cyclist) though the result can be ugly or unfortunate:
- green means on a map grass, forest, etc not a hard surface to cycle on
- pedestrian streets inside pedestrian area make the render a little ugly https://www.cyclosm.org/#map=18/48.86804/2.36516/cyclosm
So we should try to render them as a light grey.

### LINKED ISSUE #243: Quality surface tags priority order
What should be the priority order of the different quality surface tags : smoothness, surface, tracktype ?

Here we have an example with tracktype=grade2 but surface=gravel and rendered as 3rd quality surface though I was expected 2nd. (link to #242 though an other issue)
https://www.openstreetmap.org/way/658242296#map=15/49.8069/4.1521

My point of view: smoothness > tracktype > surface

### LINKED ISSUE #249: Is there a tile service for this style?
It would be lovely to have a TMS of this style on OsmAnd. Is there a tile server service available?

### PR DESCRIPTION
**Pull request by Florimondable**
Fix bicycle ramp for every steps without ramp tags.

Icons rework: (advancing in #169 #207)
Change health color to grey as hospital icon
Grey train station text & icon
Change icons size : bigger for bicycle icons and water/toilets.  fix #185 
Show bicycle amenities in lower zoom, show camp site in lower zoom.
Show police from Z16 instead of Z15.

Grey pedestrian areas, to make them look less like grass or a park. fix #239 

Add tile server url and smartphone apps to readme.

Fix quality surface tag order : smoothness > tracktype > surface, fix #243 
Render tunnel with railway and highway tag to fix, fix #234 

Capture du 2019-11-23 20-10-43
Capture du 2019-11-23 20-10-02

Fix #249.

### CODE REVIEW

**Comment by Florimondable** [comment]
Make water amenities blue and change color accommodation amenities from blue to dark green.
The water amenities are much more visible now, and I put accommodation in green to avoid to avoid too much blue (which we already have too much).

Capture du 2019-11-23 20-32-49
Capture du 2019-11-23 20-28-45

**Comment by Florimondable** [comment]
Switch some colors to make shops less catchy, and bicycle rental more.

Capture d’écran de 2019-11-23 22-18-50
Capture d’écran de 2019-11-23 22-22-31

**Comment by Florimondable** [comment]
And I'm thinking of making bicycle amenities (shops and repair stations) purple, whereas rental station go back to blue. Purple is more catchy so I'm not sure which one to emphase more ?
Here some screenshots:
Capture du 2019-11-23 22-32-32
Capture du 2019-11-23 22-31-59
Capture du 2019-11-23 22-28-21
Capture du 2019-11-23 22-28-07

**Comment by Phyks** [comment]
Sorry for late feedback on this. I had a quick look, not yet a deeper look at the code. :/

> Change health color to grey as hospital icon
> Grey train station text & icon

:+1: I would actually try to desaturate everything except bike-related icons (food shops are very high-catchy at the moment for instance). We can desaturate bank (brown) and other icons for instance IMO. My argument for this is that we want to focus on the road network and _some_ POIs, we don't have to emphasize so much the POIs.

> Grey pedestrian areas, to make them look less like grass or a park. fix #239

I don't see it much in your screenshots (Place de la République). Is it indeed done?

> Make water amenities blue and change color accommodation amenities from blue to dark green.

:+1: for having accomodations in a different color. Dark green might be too dark (depending on device / quality of screen, it is seen as almost black). I would keep about the same hue, increase a bit luminance and reduce saturation maybe ?

We could probably do the same for food shops, to have them less saturated?

> avoid too much blue (which we already have too much).

:+1:

> And I'm thinking of making bicycle amenities (shops and repair stations) purple, whereas rental station go back to blue. Purple is more catchy so I'm not sure which one to emphase more ?

There are much more bicycle amenities (shops and repair stations) than bicycle rental places, so I'd be in favor of having these in purple (more color, less blue, more eye catchy and fit for any cyclist and not only urban ones).

We should probably rework a bit the icons as well, to have a common and bolder "bicycle" feature in them (same bike for rental, shop or repair for instance).

**Comment by Florimondable** [comment]
Grey pedestrian first screenshot : https://user-images.githubusercontent.com/47089717/69483916-6049fc00-0e2d-11ea-8041-b3977fdfff80.png

>Dark green might be too dark (depending on device / quality of screen, it is seen as almost black).

Seems ok on my screens.

>There are much more bicycle amenities (shops and repair stations) than bicycle rental places, so I'd be in favor of having these in purple (more color, less blue, more eye catchy and fit for any cyclist and not only urban ones).

Not sure to understand which one you prefer. But I think that ther is much more rental station than other bikes amenities.

About POIs don’t forget that Paris is a special case: a very dense POIs place !
I will try other amenities in grey (but that not a reason to wait for merging ;)

**Comment by Florimondable** [comment]
Capture du 2019-11-29 23-11-53
Capture du 2019-11-29 23-13-42

**Pull request merged**
