### PR TITLE
Render cycleway=shared_lane

### LINKED ISSUE #148: Render shared_lane?
We currently do not render `cycleway=shared_lane`, such as https://www.openstreetmap.org/way/166351574.

In my opinion, these don't have much value for the cyclists, but might have a bit for the contributors. Not sure whether we should render them (and how)?

### PR DESCRIPTION
**Pull request by Florimondable**
Fix #148 and #173 

Before:
Capture du 2019-10-05 23-32-47

After:
Capture du 2019-10-05 23-32-56

### CODE REVIEW

**Comment by Phyks** [comment]
One remark on the code, we lack the `cycleway=opposite_shared_lane` value which is valid and quite used (most of countraflow bicycle in Paris for instance).

One question (I don't really have an opinion on this), is a `shared_lane` the same quality as a `share_busway`? I would expect the latter to be better since there is only bus and taxi drivers to worry about (limited number of vehicles, professional drivers which should in principle be aware of the bicycles etc).

**Comment by Florimondable** [comment]
There is only 26 cycleway=opposite_shared_lane, and i'm not sure that a countraflow bicycle in Paris is a shared_lane, since there is no lane... So I don't think opposite_shared_lane bring meanings.
If you want to say that the opposite direction of the way have a shared_lane cycleway:left=shared_lane is enough.

I consider third quality infrastructure as "mixed with motor vehicles" whatever they are, the main issue is the volume of traffic either way not the type.

**Comment by Phyks** [comment]
> There is only 26 cycleway=opposite_shared_lane, and i'm not sure that a countraflow bicycle in Paris is a shared_lane, since there is no lane... So I don't think opposite_shared_lane bring meanings.
> If you want to say that the opposite direction of the way have a shared_lane cycleway:left=shared_lane is enough.

Indeed, I was confusing with `cycleway=opposite`, my bad.

> I consider third quality infrastructure as "mixed with motor vehicles" whatever they are, the main issue is the volume of traffic either way not the type.

Current render is fine for me then. We might have to write something about this at some point (maybe in an enhanced legend?). Especially if we want to provide tools for local associations, so that they are aware of the way we consider things.

**Comment by Phyks** [comment]
Merged manually. Matching legend update at https://github.com/cyclosm/cyclosm-website/commit/b2fd5470164ae09a691ba135959962f95ee7f19f.

**Pull request closed without merging**
