### PR TITLE
Add waterway = dock

### PR DESCRIPTION
**Pull request by CorentinLemaitre**
I did use the same filter for the riverbank adding only dock.

### CODE REVIEW

**Comment by CorentinLemaitre** [comment]
I have use the same rule used for the waterway = riverbank to adapt it to waterway = dock

**Comment by CorentinLemaitre** [comment]
Related to issue #552

**Comment by Phyks** [comment]
Thanks for the catch and the PR! It will be part of next version.

**Comment by CorentinLemaitre** [comment]
I see no movment in the style produced online for region where there is dock ([like here](https://www.cyclosm.org/#map=16/47.2761/-2.1986/https://www.cyclosm.org/#map=16/47.2761/-2.1986/))

It is just to update it as I don't know if there is still time to wait for the style to be change online.

**Comment by Florimondable** [comment]
It’s not yet into production

**Pull request merged**
