### PR TITLE
secured bicycle parking icon rework

### PR DESCRIPTION
**Pull request by quasart**
Hello,
here is a rework of icon files for #226.

### CODE REVIEW

**Comment by Florimondable** [comment]
Nice !
The roof of the secured parking icons (squared ones) doesn’t have the same width as the other ones.
Can you correct that please ?

Can you make a snapshot of an example of the map with these new icons ?

**Comment by Phyks** [comment]
I also have a concern with limited access bicycle parkings. We currently render them with an opacity of 0.33 and this does not render very well with these new icons. Not sure how to fix this, maybe increase the size of the white inner ring?

Screenshot_2019-10-30 CyclOSM — Kosmtik

This is located at https://www.cyclosm.org/#map=20/48.85306/2.36761/cyclosm.

**Comment by quasart** [comment]
Hello,
Opacity looks applied on every subpart of the svg, and not on the icon itself. I’ll try to provide « flat » svg without overlapping shapes. It should look better.

**Comment by quasart** [comment]
I've changed the square into simple contour corners. I hope it has good rendering, but unfortunately I have no way to test it for now.

**Comment by Phyks** [comment]
Sorry for coming back late on this :/ Opacity looks good now, thanks!

Screenshot_2019-11-06 CyclOSM — Kosmtik

One minor issue, in my opinion, is that the "lock" is not strong enough. 

2Screenshot_2019-11-06 CyclOSM — Kosmtik

The only main visual difference once rendered are the small triangles in the corners.

What do you think?

For the record, the bicycle parking icons are rendered with a size of 8 pixels (could be increased a bit to 10 if required, but render is currently the same).

**Comment by Florimondable** [comment]
> For the record, the bicycle parking icons are rendered with a size of 8 pixels (could be increased a bit to 10 if required, but render is currently the same).

I try it myself, and I wasn’t happy with the result.
So I try to put the dot into a full square box, and I figure out that the icon is size fixed as you mentioned.
But I don’t like the idea to add an other rule for just the size of an icon.
May be we can try to reduce the size of the dot, or render the dot in white and the "house" in blue ?

**Comment by Phyks** [comment]
> I figure out that the icon is size fixed as you mentioned.

Current icon size is 8 pixels (width, height is determined from the marker size). We could enlarge it to 10 pixels, but it does not change much :/

**Comment by quasart** [comment]
Hello,
if width is fixed but not height, we may use height to make secured icon stronger. Here is a new try with a thicker base added :
test

**Comment by Phyks** [comment]
> if width is fixed but not height

It should be the case, and indeed it should be fine to have non-square icons.

> Here is a new try with a thicker base added :

Looks better! Maybe we should make the top stronger as well?

2Screenshot_2019-11-06 CyclOSM — Kosmtik

**Comment by quasart** [comment]
The top of the « covered » icons ? I kept the uncovered one light to make clear difference

**Comment by Phyks** [comment]
> The top of the « covered » icons ?

Yes, only for the covered ones (actually,the locked ones). Currently, the locked ones have a strong basis and a lighter top. What about locking symmetrically?

**Comment by quasart** [comment]
Here I tried to make top of lock stronger for both covered and uncovered secured

**Comment by Phyks** [comment]
Thanks!

**Comment by Florimondable** [comment]
Result for the record :
Capture du 2019-11-23 21-52-29

**Pull request merged**
