### PR TITLE
Render leisure track bicycle for areas

### LINKED ISSUE #440: Render leisure=track+sport=cycling area like the linear ones
see #412

### PR DESCRIPTION
**Pull request by Florimondable**
Fix #440 and #442

image
image

### CODE REVIEW

**Comment by quasart** [comment]
Hello !

In this fix, area borders and way tracks are rendered the same way, I find this confusing. 
In the Velodrome Anquetil example, we may understand there are two concentric tracks.

Here is a try with an area fill :
Screen Shot

And in your bicross example, I understand it's actually not an area. Rendering would already look nice with explicit "area=no" tagging (advised tagging in OSM wiki)

Cheers

**Comment by Florimondable** [comment]
> Hello !
> 
> In this fix, area borders and way tracks are rendered the same way,
Yeah, that's the trick so area or linear ways can be mixed properly.

**Comment by Phyks** [comment]
What about https://postgis.net/docs/ST_ExteriorRing.html? (Performance should be tested)

**Comment by Florimondable** [comment]
> What about https://postgis.net/docs/ST_ExteriorRing.html? (Performance should be tested)

Not convinced by the rendering result it'd make.

**Comment by Phyks** [comment]
In the case of https://user-images.githubusercontent.com/47089717/101991384-a7ab6080-3cac-11eb-8582-12ed46b5673b.png, it would return only the outer ring (which is the outer purple line). Then, it should discard the misleading inner loop.

**Comment by Florimondable** [comment]
I don't fill it's that much missleading.

**Comment by quasart** [comment]
> Yeah, that's the trick so area or linear ways can be mixed properly.

I understand the trick, it’s a smart try but i think It’s not worth the confusion it creates :
- it may mislead the map reader
- For developpers, it hard to choose appropriate rendering style. In your example violet casing disappear at z14 : this is good for #442 but bad for #440

I think KISS principle Is better here : Bold purpul for lines, and lighter purpul for areas

**Comment by Florimondable** [comment]
Let me explain the problem again :
we have leisure=track closed way which is considered polygon by osm2pgsql, where as I consider as OSM Carto they are linear way.
I cannot change current osm2pgsql conf.

So I had to find a middle ground where both areas and linear leisure=track are well drawn.

**Comment by quasart** [comment]
I understood that very well. I guess my answer is not clear.

Since we cannot know if a polygon is an actual area or a closed I see two solution :
1. a "middle ground" rendering style looking like both an area and a track
2. always render it as an area

I'm saying (1) is confusing for both map reader and style developer.

Solution (2) is KISS and we still may advise OSM contributor to add explicit `area=no` if they want clean rendering. It's recommended tagging anyway.

**Comment by Florimondable** [comment]
@Phyks Can I merge it, so we can move forward ?

**Comment by Phyks** [comment]
Hi,

Sorry, this one slipped out of my sight :/ I'm still a bit puzzled by the rendering, which seems a bit misleading for me. From the OSM wiki, I see

> It's unclear/undecided whether closed ways should be treated as areas for this tag so it is advised to always add an area=yes/no tag in the case of closed ways. The default OSM Carto stylesheet displays an area only if area=yes is present. This is not necessary for multipolygons since they are always handled as areas. 

I think OSM carto approach is nice (requiring an explicit `area=yes`) but this needs tweaking osm2pgsql, which we don't want to do. I, however, think we can achieve the same thing by tweaking SQL queries. That is:

The current `leisure_track` is enough to target **only** the linear `leisure=track`:
```
- id: leisure_track
  <<: *extents
  Datasource:
    <<: *osm2pgsql
    table: |-
      (
        SELECT
          way,
          sport
        FROM planet_osm_line
        WHERE leisure = 'track'
      ) AS data
  geometry: linestring
  properties:
    cache-features: true
    minzoom: 11
``` 

We have to add rendering for areas `leisure=track`, without perturbing this one. We have to :
- include those with an explicit `area=yes`, e.g. https://www.openstreetmap.org/way/787733437
- include those which come from a `multipolygon` relation, as they are to be treated as areas by default, e.g. https://www.openstreetmap.org/relation/3214796
- exclude any closed way without explicit `area=yes`, e.g. https://www.openstreetmap.org/way/158239095

This can be done with the following SQL query:

```sql
SELECT
    osm_id,
    leisure
FROM (
    -- Distinguish two cases: either there is an explicit area=yes or this is coming from a realtion with multipolygon type
    (
        SELECT
            planet_osm_polygon.osm_id,
            planet_osm_polygon.leisure,
            true AS is_area
        FROM planet_osm_polygon
        WHERE
            -- Fixed input list of osm_id for testing. Should be way && !bbox! in production
            osm_id IN (787733437, -3214796, 158239095)
            AND area='yes'
    )
    UNION
    (
        SELECT
            planet_osm_polygon.osm_id,
            planet_osm_polygon.leisure,
            planet_osm_rels.tags @> '{type, multipolygon}' AS is_area
        -- osm_id handling is different across these two tables, hence the need for -1 multiplication
        FROM planet_osm_polygon LEFT JOIN planet_osm_rels ON planet_osm_polygon.osm_id = - planet_osm_rels.id
        WHERE
            -- Fixed input list of osm_id for testing. Should be way && !bbox! in production
            osm_id IN (787733437, -3214796, 158239095)
            AND osm_id < 0
            AND (area IS NULL OR area != 'yes')
    )
) AS data;
```

This is quite slow at the moment due to the osm_id trick for relations. I guess this could be achievable in production by adding an index on this, to be checked.

This can be quite heavily simplified if we only consider explicit `area=yes` ways (even for multipolygons).

**Comment by Florimondable** [comment]
So yeah, it's over complicated for not much in my opinion.

**Pull request closed without merging**
