### PR TITLE
Add xmas tree and market at the end of December.

### PR DESCRIPTION
**Pull request by Florimondable**
I had time to loose 🎅

Only rendered after 15 of December.

image

### CODE REVIEW

**Comment by Florimondable** [comment]
May be we can set the date earlier.

**Comment by Phyks** [comment]
🎉 

But I think you forgot the svg files :)

**Comment by Florimondable** [comment]
Here it is.
(forgotten as always :sweat: )

**Comment by Phyks** [comment]
This is now in production along with v0.4! \o/

**Pull request merged**
