### PR TITLE
Greener tracks

### PR DESCRIPTION
**Pull request by brainwad**
Shift the hue of the tracks from 214° (very close to the hue of mixed-cycle-fill, which is 217°) to 140° (matching the hue of nomotor-fill), while maintaining the lightness and saturation. For reference, the hue of path-fill is 170° and cycle-fill is 240°, so with this change there is a continuum from roads that are (mostly) closed to motor vehicles (greenest) through paths that are either allowed or designated for bikes, but not reserved, to dedicated cycleways (bluest).

base vs 
this change.

The screenshots show a variety of backgrounds. I think the tracks are still quite visible even over forests, but it does stand out less there than the blue does. On other backgrounds (grass, farmland, plain) they are about the same.

### CODE REVIEW

**Comment by brainwad** [comment]
This would partially address #401

**Comment by Florimondable** [comment]
Hi, thanks for the work, I like the idea.
I choose a dark blue because :
- must be visible easily (I like gravel biking) in the country and in the wood at low zoom (like here https://www.cyclosm.org/#map=12/49.3189/4.3005/cyclosm_live), so you can trace a route easily for tenth of kilometers.
- I understand that since they are shared road they should be more green than blue

So, can you make a try with a darker green, colors is difficult because to choose, our color perception is not as easy as math ;)

**Comment by brainwad** [comment]
I matched the contrast ratio of the old colour against the forest background (5.3:1), and it seems to be "as dark" to me now. The green-ness is less pronounced, of course, but it's still further away from the cycleway colour than before. Sorry I don't have France downloaded, but I tried to find a similar area of Switzerland :)

z12
z15

**Comment by Phyks** [comment]
@Florimondable What's the status on this one? Is it a go for a merge? (I see a thumb up on latest screenshot)

**Comment by Florimondable** [comment]
It was not a go for a merge. Nevermind, I may going to tweak the colors
.

**Comment by Florimondable** [comment]
Merged !
Nice to see it on a live map, green tracks make them more understandable and look nice, thank you for your work.

**Pull request merged**
