### PR TITLE
Give bridges for large roads a dark border on zoom >= 14

### PR DESCRIPTION
**Pull request by hiddewie**
This gives a better feeling for the relations between roads. Should mostly solve #277.

Before 

image

After

image

### CODE REVIEW

**Comment by hiddewie** [comment]
BTW (other issue) there is a motorway trunk rendered on top of (I think) a primary road. It should be rendered behind it (any trunk road should be rendered behind any other non-trunk road).

**Comment by Florimondable** [comment]
How does it render if the bridge has cycle lane/track like here ? https://www.cyclosm.org/#map=19/52.35050/6.64542/cyclosm

And I think the color should be more grey, like 666 or 888.

Can you provide a screenshot for these ?

**Comment by hiddewie** [comment]
Those roads are not affected. Any bicycle infrastructure along a road should override this rendering of the bridge.

image

I changed the color to `#666`, that is good.

image

**Comment by Florimondable** [comment]
Ok, thank you, it’s fine for me 😃

**Comment by Phyks** [comment]
Thanks for the PRs! I was investigating issues we discussed by emails due to some issues with our server infrastructure and low zooms (< Z11) not necessarily being up to date. This should now be solved. I'll have a look ASAP at your PRs on the code and merge!

**Comment by Phyks** [comment]
Thanks for this PR!

**Comment by Phyks** [comment]
> BTW (other issue) there is a motorway trunk rendered on top of (I think) a primary road. It should be rendered behind it (any trunk road should be rendered behind any other non-trunk road).

Would you have the OSM ids involved here please?

**Comment by hiddewie** [comment]
@Phyks I just tried using the (live) web interface, and could not reproduce the last problem. I'll make an issue if I can find it again.

**Comment by Phyks** [comment]
Thanks for the update!

**Pull request merged**
